name: Github Actions를 활용한 CI/CD 구축

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Github Actions 테스트하기
              run: echo "Github Actions 테스트"